name: C program
on: [push, workflow_dispatch]

jobs:
  test1:
    runs-on: macos-latest
    steps:
      - name: Run Commands
        run: sudo gcc -v
      
      - name: PMD Code Analyzer Action
      # You may pin to the exact commit or the version.
        uses: billyan2018/setup-pmd@1.2 
      
      # - uses: sfdx-actions/setup-pmd@v1
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: run-pmd
      #  run: pmd -d ./force-app/main/default/classes -R category/apex/design.xml -f text
