name: PMD source check
on: [push]
jobs:
  pmd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: krukmat/setup-pmd@v0.4
      - run: npm run apex-pmd
      
BEGIN PACKAGE.JSON FILE
{
  "scripts": {
    "apex-pmd": "pmd -d sourceFolderName -R ci/pmd.xml -f text"
  },
}

BEGIN pmd.xml FILE

<?xml version="1.0"?>

<ruleset name="Braces"
  xmlns="http://pmd.sourceforge.net/ruleset/2.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://pmd.sourceforge.net/ruleset/2.0.0 https://pmd.sourceforge.io/ruleset_2_0_0.xsd">
<description>
The Braces ruleset contains rules regarding the use and placement of braces.
</description>

  <rule ref="category/apex/codestyle.xml/ForLoopsMustUseBraces" deprecated="true" />
  <rule ref="category/apex/codestyle.xml/IfElseStmtsMustUseBraces" deprecated="true" />
  <rule ref="category/apex/codestyle.xml/IfStmtsMustUseBraces" deprecated="true" />
  <rule ref="category/apex/codestyle.xml/WhileLoopsMustUseBraces" deprecated="true" />

</ruleset>
